# Generated by Django 5.1.4 on 2025-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="tweet",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="tweets", to="tweets.hashtag"
            ),
        ),
    ]
