# Generated by Django 5.1.4 on 2025-01-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directmessage",
            old_name="Content",
            new_name="content",
        ),
    ]
