# Generated by Django 5.1.4 on 2025-01-19 07:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="default_profile.png",
                upload_to=users.models.upload_profile_image_path,
            ),
        ),
    ]
